export enum actionTypes {
	FETCH_CHARACTER = 'FETCH_CHARACTER',
	FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS',
	FETCH_CHARACTER_FAILURE = 'FETCH_CHARACTER_FAILURE',
	START_FETCHING_CHARACTERS = 'START_FETCHING_CHARACTERS',
	STOP_FETCHING_CHARACTERS = 'STOP_FETCHING_CHARACTERS'
}
